## PyTorch Fundamentals

### Import libraries

In [1]:
import torch

torch.__version__

'1.13.0'

### Introdunction to Tensors

**Note:** Three common errors:
1. Tensors with incorrect datatype
2. Tensors with unmatched shape
3. Tensors running on the different devices

### Create Tensors


#### Creating tensors using [`torch.tensor()`](https://pytorch.org/docs/stable/tensors.html).

In [2]:
#Scalar
s = torch.tensor(7)
s

tensor(7)

In [3]:
#Vector
v = torch.tensor([1,2])
v

tensor([1, 2])

In [4]:
#Matrix
m = torch.tensor([[1,2],
                  [3,4]])
m

tensor([[1, 2],
        [3, 4]])

In [5]:
#Tensor
t = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

#### Creating random tensors
Initialize tensors with random numbers.
- [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) returns a tensor filled with random numbers from a **uniform distribution** on the interval [0,1).
- [`torch.randint()`](https://pytorch.org/docs/stable/generated/torch.randint.html) returns a tensor filled with **random integers generated uniformly** between [low, high).
- [`torch.randn()`](https://pytorch.org/docs/stable/generated/torch.randn.html)
returns a tensor filled with random numbers from a **standard normal distribution**.
- [`torch.randperm()`](https://pytorch.org/docs/stable/generated/torch.randperm.html) returns a **random permutation of integers** from [0,n).



In [6]:
#input size
print(torch.rand(4))
print(torch.rand(2, 3))

tensor([0.0623, 0.2877, 0.6236, 0.1281])
tensor([[0.8678, 0.0518, 0.3245],
        [0.4371, 0.1730, 0.2429]])


In [7]:
#input low, high, size. default low = 0.
print(torch.randint(3, 5, (3,)))
print(torch.randint(10, (2, 2)))

tensor([3, 3, 3])
tensor([[8, 0],
        [9, 4]])


In [8]:
#input size
print(torch.randn(4))
print(torch.randn(2, 3))

tensor([-0.6453, -1.0850, -0.6521,  1.3741])
tensor([[-0.7506, -0.0439, -1.9226],
        [-1.8010, -0.4398,  0.3543]])


In [9]:
#input upper bound n (exclusive)
print(torch.randperm(4))

tensor([2, 0, 3, 1])


#### Zeros and ones and other values
Initialize tensors with specific values.
- [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html#torch.zeros) returns a tensor filled with **the scalar value 0**.
- [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html#torch.ones) returns a tensor filled with **the scalar value 1**.
- [`torch.full()`](https://pytorch.org/docs/stable/generated/torch.full.html#torch.full)
returns a tensor filled with **fill_value**.




In [10]:
print(torch.zeros(2, 3))
print(torch.ones(2, 3))
print(torch.full((2, 3), 3))


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3, 3, 3],
        [3, 3, 3]])


#### Creating a range of tensors
- [`torch.arange()`](https://pytorch.org/docs/stable/generated/torch.arange.html) returns a 1-D tensor of size $\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil$ with values from the interval `[start, end)` taken with common difference `step` beginning from `start`.
- [`torch.linspace()`](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch.linspace) creates a 1-D tensor of size steps whose values are evenly spaced from [`start`, `end`].

In [11]:
#input start, end, step. default start = 0.
print(torch.arange(5))
print(torch.arange(1, 4))
print(torch.arange(1, 100, 7))

tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3])
tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])


In [12]:
#input start, end, step
print(torch.linspace(3, 10, 5))
print(torch.linspace(1, 4, 4))
print(torch.linspace(1, 100, 1))

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1., 2., 3., 4.])
tensor([1.])


#### Creating tensors with tensor-like


In [13]:
t, t.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [14]:
print(torch.zeros_like(t))
print(torch.ones_like(t))
print(torch.full_like(t, fill_value = 8))


tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])
tensor([[[8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]]])


### Tensor attributes

- `tensor.ndim` shows the dimention while `tensor.shape` shows the size/shape.

- Intuitively, `tensor.ndim` is equal to the number left brackets at beginning.

In [15]:
print('scalar')
print(s)
print(s.ndim)
print(s.shape)
print()
print('vector')
print(v)
print(v.ndim)
print(v.shape)
print()
print('matrix')
print(m)
print(m.ndim)
print(m.shape)
print()
print('tensor')
print(t)
print(t.ndim)
print(t.shape)


scalar
tensor(7)
0
torch.Size([])

vector
tensor([1, 2])
1
torch.Size([2])

matrix
tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])

tensor
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


- `tensor.item()` converts one-element tensor to Python scalars

In [16]:
s.item()

7

- `tensor[]` slices tensors

- : indicates the range. e.g. [start, end)

- , splits the dims.

In [17]:
print(m[0])     #shows the first row, equals m[0,:]
print(m[:,0])   #shows the first column

tensor([1, 2])
tensor([1, 3])


In [18]:
print(t[0])     
print(t[:,0])   
print(t[:,:,0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3]])
tensor([[1, 4, 7]])


- `tensor.dtype` shows the data type of the tensor. `tensor.type()` changes datatype.

- `torch.device` is an object representing the device (`'cpu'` or `'cuda'`) on which a `torch.Tensor` is or will be allocated. `tensor.to()` changes the allocated device.

In [19]:
t.dtype, t.device

(torch.int64, device(type='cpu'))

In [20]:
t.type(torch.float32), t.to('cpu')

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

### Tensor manipulation

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Power
* Matrix multiplication
* Transpose


In [39]:
m

tensor([[1, 2],
        [3, 4]])

In [40]:
m + 10, m.add(10)

(tensor([[11, 12],
         [13, 14]]),
 tensor([[11, 12],
         [13, 14]]))

In [41]:
m - 1, m.sub(1)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[0, 1],
         [2, 3]]))

In [42]:
m * 2, m.mul(2)

(tensor([[2, 4],
         [6, 8]]),
 tensor([[2, 4],
         [6, 8]]))

In [25]:
m / 2, m.div(2)

(tensor([[[0.5000, 1.0000, 1.5000],
          [2.0000, 2.5000, 3.0000],
          [3.5000, 4.0000, 4.5000]]]),
 tensor([[[0.5000, 1.0000, 1.5000],
          [2.0000, 2.5000, 3.0000],
          [3.5000, 4.0000, 4.5000]]]))

In [30]:
m ** 2, m.pow(2)

(tensor([[[ 1,  4,  9],
          [16, 25, 36],
          [49, 64, 81]]]),
 tensor([[[ 1,  4,  9],
          [16, 25, 36],
          [49, 64, 81]]]))

In [43]:
m * m, m.mul(m)

(tensor([[ 1,  4],
         [ 9, 16]]),
 tensor([[ 1,  4],
         [ 9, 16]]))

In [64]:
m @ m, m.matmul(m), m.mm(m)

(tensor([[ 7, 10],
         [15, 22]]),
 tensor([[ 7, 10],
         [15, 22]]),
 tensor([[ 7, 10],
         [15, 22]]))

In [69]:
m, m.T

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 3],
         [2, 4]]))

### Tensor aggregation
- `tensor.min()`
- `tensor.max()`
- `tensor.mean()` **Note:** input tensor dtype should be float or complex
- `tensor.sum()`
- `tensor.median()`



In [79]:
x = torch.arange(start=1, end=100, step=7, dtype=torch.float32)
x

tensor([ 1.,  8., 15., 22., 29., 36., 43., 50., 57., 64., 71., 78., 85., 92.,
        99.])

In [81]:
x.min(), x.max(), x.mean(), x.sum(), x.median()

(tensor(1.), tensor(99.), tensor(50.), tensor(750.), tensor(50.))

### Tensor min/max position
- `tensor.argmin()`
- `tensor.argmax()`
- `tensor.argsort()` returns the indices that sort a tensor along a given dimension in ascending order by value.

In [84]:
x = torch.rand(3,3)
x

tensor([[0.3930, 0.7333, 0.4506],
        [0.5365, 0.6073, 0.6738],
        [0.7048, 0.9071, 0.8163]])

In [88]:
x.argmin(), x.argmax()

(tensor(0), tensor(7))

In [92]:
x.argsort(dim=0), x.argsort(dim=1)

(tensor([[0, 1, 0],
         [1, 0, 1],
         [2, 2, 2]]),
 tensor([[0, 2, 1],
         [0, 1, 2],
         [0, 2, 1]]))

### Tensor reshape, stack, squeeze and unsqueeze
- `tensor.reshape()` is equal to `tensor.view()` if `tensor.is_contiguous()` else `tensor.congiguous().view()`
- 
- 

In [93]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
x.reshape(1,-1), x.view(1,-1)

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [97]:
print(x)
x.reshape(1,-1)[0] = 5
print(x)

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
