## PyTorch Fundamentals

### Import libraries

In [123]:
import torch

torch.__version__

'1.13.0'

### Introdunction to Tensors

**Note:** Three common errors:
1. Tensors with incorrect datatype
2. Tensors with unmatched shape
3. Tensors running on the different devices

### Create Tensors


#### Creating tensors using [`torch.tensor()`](https://pytorch.org/docs/stable/tensors.html).

In [124]:
#Scalar
s = torch.tensor(7)
s

tensor(7)

In [125]:
#Vector
v = torch.tensor([1,2])
v

tensor([1, 2])

In [126]:
#Matrix
m = torch.tensor([[1,2],
                  [3,4]])
m

tensor([[1, 2],
        [3, 4]])

In [127]:
#Tensor
t = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

#### Creating random tensors
Initialize tensors with random numbers.
- [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) returns a tensor filled with random numbers from a **uniform distribution** on the interval [0,1).
- [`torch.randint()`](https://pytorch.org/docs/stable/generated/torch.randint.html) returns a tensor filled with **random integers generated uniformly** between [low, high).
- [`torch.randn()`](https://pytorch.org/docs/stable/generated/torch.randn.html)
returns a tensor filled with random numbers from a **standard normal distribution**.
- [`torch.randperm()`](https://pytorch.org/docs/stable/generated/torch.randperm.html) returns a **random permutation of integers** from [0,n).



In [128]:
#input size
print(torch.rand(4))
print(torch.rand(2, 3))

tensor([0.9017, 0.1077, 0.8662, 0.6825])
tensor([[0.6908, 0.3300, 0.8046],
        [0.7606, 0.8698, 0.4297]])


In [129]:
#input low, high, size. default low = 0.
print(torch.randint(3, 5, (3,)))
print(torch.randint(10, (2, 2)))

tensor([3, 4, 4])
tensor([[0, 0],
        [9, 8]])


In [130]:
#input size
print(torch.randn(4))
print(torch.randn(2, 3))

tensor([-0.5305, -0.5016, -0.5981, -0.7841])
tensor([[-0.1742,  0.1151, -0.1927],
        [-0.3984, -0.9073,  0.6363]])


In [131]:
#input upper bound n (exclusive)
print(torch.randperm(4))

tensor([1, 0, 3, 2])


#### Zeros and ones and other values
Initialize tensors with specific values.
- [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html#torch.zeros) returns a tensor filled with **the scalar value 0**.
- [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html#torch.ones) returns a tensor filled with **the scalar value 1**.
- [`torch.full()`](https://pytorch.org/docs/stable/generated/torch.full.html#torch.full)
returns a tensor filled with **fill_value**.




In [132]:
print(torch.zeros(2, 3))
print(torch.ones(2, 3))
print(torch.full((2, 3), 3))


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3, 3, 3],
        [3, 3, 3]])


#### Creating a range of tensors
- [`torch.arange()`](https://pytorch.org/docs/stable/generated/torch.arange.html) returns a 1-D tensor of size $\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil$ with values from the interval `[start, end)` taken with common difference `step` beginning from `start`.
- [`torch.linspace()`](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch.linspace) creates a 1-D tensor of size steps whose values are evenly spaced from [`start`, `end`].

In [133]:
#input start, end, step. default start = 0.
print(torch.arange(5))
print(torch.arange(1, 4))
print(torch.arange(1, 100, 7))

tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3])
tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])


In [134]:
#input start, end, step
print(torch.linspace(3, 10, 5))
print(torch.linspace(1, 4, 4))
print(torch.linspace(1, 100, 1))

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1., 2., 3., 4.])
tensor([1.])


#### Creating tensors with tensor-like


In [135]:
t, t.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [136]:
print(torch.zeros_like(t))
print(torch.ones_like(t))
print(torch.full_like(t, fill_value = 8))


tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])
tensor([[[8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]]])


### Tensor attributes

`tensor.ndim` shows the dimention while `tensor.shape` shows the size/shape.

Intuitively, `tensor.ndim` is equal to the number left brackets at beginning.

In [137]:
print('scalar')
print(s)
print(s.ndim)
print(s.shape)
print()
print('vector')
print(v)
print(v.ndim)
print(v.shape)
print()
print('matrix')
print(m)
print(m.ndim)
print(m.shape)
print()
print('tensor')
print(t)
print(t.ndim)
print(t.shape)


scalar
tensor(7)
0
torch.Size([])

vector
tensor([1, 2])
1
torch.Size([2])

matrix
tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])

tensor
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


`tensor.item()` converts one-element tensor to Python scalars

In [138]:
s.item()

7

`tensor[]` slices tensors

: indicates the range. e.g. [start, end)

, splits the dims.

In [139]:
print(m[0])     #shows the first row, equals m[0,:]
print(m[:,0])   #shows the first column

tensor([1, 2])
tensor([1, 3])


In [140]:
print(t[0])     
print(t[:,0])   
print(t[:,:,0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3]])
tensor([[1, 4, 7]])


`tensor.dtype` shows the data type of the tensor. `tensor.type()` changes datatype.

`torch.device` is an object representing the device (`'cpu'` or `'cuda'`) on which a `torch.Tensor` is or will be allocated. `tensor.to()` changes the allocated device.

In [141]:
t.dtype, t.device

(torch.int64, device(type='cpu'))

In [142]:
t.type(torch.float32), t.to('cpu')

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))