# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
t1 = torch.rand(7,7)
t1

tensor([[0.4718, 0.8910, 0.9467, 0.0461, 0.5315, 0.3704, 0.5463],
        [0.0111, 0.2728, 0.4565, 0.3559, 0.3818, 0.5260, 0.6197],
        [0.1697, 0.1372, 0.5730, 0.6006, 0.3034, 0.4175, 0.8701],
        [0.4381, 0.6069, 0.9609, 0.7080, 0.9410, 0.9344, 0.1729],
        [0.1784, 0.0726, 0.9268, 0.7174, 0.5059, 0.0486, 0.3632],
        [0.5533, 0.9327, 0.6029, 0.7711, 0.8599, 0.0862, 0.9497],
        [0.8586, 0.4102, 0.8353, 0.3776, 0.7401, 0.7137, 0.5824]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
t2 = torch.rand(1,7)
# Perform matrix multiplication 
t1 @ t2.T

tensor([[1.6166],
        [1.1007],
        [1.2371],
        [1.3540],
        [0.6829],
        [2.1307],
        [1.4773]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(7,7)
t2 = torch.rand(1,7)

# Matrix multiply tensors
t1 @ t2.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Device:', device)
# Create two random tensors on GPU
t1 = torch.rand(2, 3).to(device)
t2 = torch.rand(2, 3).to(device)
t1, t2

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
output = t1 @ t2.T
output

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
print(output.max())
# Find min
print(output.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max

print(output.argmin())
# Find arg min
print(output.argmax())

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed

torch.manual_seed(7)
# Create random tensor
t1 = torch.rand((1,1,1,10))
# Remove single dimensions
t2 = t1.squeeze()
# Print out tensors and their shapes
print(t1, t1.shape)
print(t2, t2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
